spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: btg-funds
  main:
    web-application-type: reactive
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

business:
  initial-balance: ${BUSINESS_INITIAL_BALANCE}
  from-email: ${SES_MAIL}
  twilio-phone: ${TWILIO_PHONE}

dynamodbAws:
  customers-table: ${DYNAMODB_CUSTOMERS_TABLE}
  funds-table: ${DYNAMODB_FUNDS_TABLE}
  transactions-table: ${DYNAMODB_TRANSACTIONS_TABLE}

aws:
  region: ${AWS_REGION}
  endpoint: ${AWS_ENDPOINT}
  ses-endpoint: ${AWS_SES_ENDPOINT:}
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}

twilio:
  sid: ${TWILIO_SID}
  token: ${TWILIO_TOKEN}
  messaging-service-sid: ${TWILIO_MESSAGING_SERVICE_SID:}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  auth:
    demo-username: ${DEMO_USERNAME}
    demo-password: ${DEMO_PASSWORD}

logging:
  level:
    root: INFO
    com.btg.funds: DEBUG